// Script untuk membuat post di Blogspot dengan isi artikel dari AI Gemini

const axios = require('axios');

const GEMINI_API_KEY = 'AIzaSyAnPO90a0Q2nF4SrxGV07EnGfYh-PQwHyw';
const BLOGGER_API_KEY = 'AIzaSyCVxytTOozO9H3Sv_pQReCYUZ6SWyI_wkQ';
const BLOG_ID = '6550260102335539072';

async function generateArticle(title) {
    try {
        const geminiResponse = await axios.post(
            `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${GEMINI_API_KEY}`,
            {
                contents: [{
                    parts: [{ text: title }]
                }]
            },
            { headers: { 'Content-Type': 'application/json' } }
        );

        console.log('Gemini API response:', JSON.stringify(geminiResponse.data, null, 2));

        const articleContent = geminiResponse.data.candidates?.[0]?.content?.parts?.[0]?.text;

        if (!articleContent) {
            throw new Error('No content generated by Gemini AI');
        }

        return articleContent;
    } catch (error) {
        console.error('Error generating article:', error.response ? error.response.data : error.message);
        throw error;
    }
}

async function postToBlogspot(title, content) {
    try {
        const blogspotResponse = await axios.post(
            `https://www.googleapis.com/blogger/v3/blogs/${BLOG_ID}/posts/`,
            {
                title: title,
                content: content
            },
            { headers: { 'Authorization': `Bearer ${BLOGGER_API_KEY}` } }
        );

        console.log('Blogspot API response:', blogspotResponse.data);

        return blogspotResponse.data;
    } catch (error) {
        console.error('Error posting to Blogspot:', error.response ? error.response.data : error.message);
        throw error;
    }
}

async function createPost(title) {
    try {
        const content = await generateArticle(title);
        const post = await postToBlogspot(title, content);
        console.log('Post successfully created:', post.url);
    } catch (error) {
        console.error('Error creating post:', error);
    }
}

// Contoh penggunaan
createPost('How AI Transforms Content Creation');
